ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
    platform: Windows 7
  - name: safari
    version: latest
    platform: OS X 10.10
  - name: firefox
    version: latest
    platform: Windows 7
  - name: ie
    version: 6..8
    platform: Windows XP
  - name: ie
    version: 9..11
    platform: Windows 7
